name: Release
on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Cache Playwright dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-playwright
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup 1Password Connect
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Setup
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          KAGI_TOKEN: "op://Github Actions/kagi/credential"
      - name: Run tests
        run: cargo test
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        name: Get Tag Name
        with:
          tagRegex: "v(?<version>.*)"
      - name: Set Package Version
        env:
          GIT_TAG_NAME: ${{ steps.tagName.outputs.version }}
        run: sed -i "s/version = \"\([^)]*\)\"/version = \"${GIT_TAG_NAME}\"/" Cargo.toml
      - name: Cargo Login
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: cargo login $CARGO_TOKEN
      - name: Cargo Publish Dry Run
        run: cargo publish --dry-run
      - name: Cargo Publish
        run: cargo publish
